swagger: 2.0
info:
  title: Model API
  version: 0.0.1
  description: Describes an API interface to a machine learning service
  contact:
    email: zach.glassman@gmail.com
    name: Zachary Glassman
paths:
  /features:
    summary: Features of the model
    get:
      summary: get all features
      description: Gets all the features of the model along with their ids
      operationId: 'getFeatures'
      responses:
        default:
          description: Default error sample response
  /features/{featureId}:
    summary: Info about particular features
    get:
      operationId: 'getFeature'
      summary: get a single feature
      parameters:
        - name: featureId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feature"

  /model/description:
    summary: Description of the model
    get:
      responses:
        default:
          description: Default response

components:
  schemas:
    Feature:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
